# run make test for python

name: Python Tests

on:
  - pull_request

jobs:
  python-translations:
    runs-on: ubuntu-latest

    steps:
      # Define which file extensions, when touched, should trigger the
      # Python tests, so we can skip this Action if we've only touched .po files
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            non_pofiles:
              - '**.txt'
              - '**.yml'
              - '**.in'
              - '**.py'

      # Clones the openedx-translations repo
      - name: clone openedx/openedx-translations
        uses: actions/checkout@v6

      - name: Setup node for testing
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install nodejs requirements
        run: |
          npm clean-install

      - name: Install gettext
        if: steps.filter.outputs.non_pofiles == 'true'
        run: |
          sudo apt install -y gettext

      # Sets up Python
      - name: setup python
        if: steps.filter.outputs.non_pofiles == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Run the script
      - name: run python tests
        if: steps.filter.outputs.non_pofiles == 'true'
        run: |
          make test_requirements
          make test
